// devopsfront/src/views/warehouse/warehouse.vue
<script lang="ts" setup>
  import { ref, reactive, onMounted } from 'vue';
  import { Message } from '@arco-design/web-vue';
  import {
    IconPlus,
    IconSync,
    IconEye,
    IconDelete,
    IconEdit,
  } from '@arco-design/web-vue/es/icon';
  import { useI18n } from 'vue-i18n';
  import dayjs from 'dayjs';
  import {
    getRepositories,
    createRepository,
    updateRepository,
    deleteRepository,
  } from '@/api/warehouse';
  import type { Repository } from '@/api/warehouse';

  const { t } = useI18n();

  const loading = ref(false);
  const repositories = ref<Repository[]>([]);
  const modalVisible = ref(false);
  const editingId = ref<number | null>(null);
  const formRef = ref();

  const form = ref({
    name: '',
    url: '',
    token: '',
  });

  const rules = {
    name: [{ required: true, message: '请输入仓库名称' }],
    url: [{ required: true, message: '请输入仓库地址' }],
    token: [{ required: true, message: '请输入访问令牌' }],
  };

  // 获取仓库列表
  const fetchRepositories = async () => {
    loading.value = true;
    try {
      console.log('获取仓库列表');
      const res = await getRepositories();
      console.log(res,"111")
      // repositories.value
      console.log('获取到的仓库列表:', repositories.value);
      repositories.value = res
    } catch (error) {
      console.error('获取仓库列表失败:', error);
      Message.error('获取仓库列表失败');
    } finally {
      loading.value = false;
    }
  };

  // 打开模态框
  const openModal = (record?: Repository) => {
    if (record) {
      editingId.value = record.id;
      form.value = { ...record };
    } else {
      editingId.value = null;
      form.value = {
        name: '',
        url: '',
        token: '',
      };
    }
    modalVisible.value = true;
  };

  // 关闭模态框
  const closeModal = () => {
    modalVisible.value = false;
    formRef.value?.resetFields();
  };

  // 提交表单
  const handleSubmit = async () => {
    try {
      const valid = await formRef.value?.validate();
      // if (!valid) {
      //   console.log('表单验证失败');
      //   return;
      // }

      const formData = {
        name: form.value.name,
        platform: 'github', // 默认使用 GitHub
        url: form.value.url,
        token: form.value.token,
        defaultBranch: 'main', // 默认分支
        status: 'active', // 默认状态
      };

      console.log('准备提交数据:', formData);

      if (editingId.value) {
        console.log('更新仓库:', editingId.value);
        await updateRepository(editingId.value, formData);
        Message.success('仓库更新成功');
      } else {
        console.log('创建新仓库');
        await createRepository(formData);
        Message.success('仓库创建成功');
      }
      closeModal();
      fetchRepositories();
    } catch (error) {
      console.error('提交失败:', error);
      Message.error('操作失败');
    }
  };

  // 删除仓库
  const handleDelete = async (id: number) => {
    try {
      await deleteRepository(id);
      Message.success('仓库删除成功');
      fetchRepositories();
    } catch (error) {
      Message.error('删除失败');
    }
  };

  // 获取平台颜色
  const getPlatformColor = (platform: Repository['platform']) => {
    const colors: Record<Repository['platform'], string> = {
      github: 'blue',
      gitlab: 'orange',
      gitee: 'red',
    };
    return colors[platform] || 'gray';
  };

  // 获取状态颜色
  const getStatusColor = (status: Repository['status']) => {
    const colors: Record<Repository['status'], string> = {
      active: 'green',
      inactive: 'gray',
      error: 'red',
    };
    return colors[status] || 'gray';
  };

  // 格式化日期
  const formatDate = (date: string) => {
    return new Date(date).toLocaleString();
  };

  onMounted(() => {
    fetchRepositories();
  });
</script>

<template>
  <div class="warehouse-container">
    <a-card class="general-card" :title="$t('仓库管理')">
      <template #extra>
        <a-button type="primary" @click="openModal()">
          <template #icon><icon-plus /></template>
          {{ $t('添加仓库') }}
        </a-button>
      </template>
      <a-table
        :data="repositories"
        :loading="loading"
        :pagination="false"
        :bordered="false"
      >
        <template #columns>
          <a-table-column :title="$t('仓库名称')" data-index="name" />
          <a-table-column :title="$t('仓库地址')" data-index="url" />
          <a-table-column :title="$t('默认分支')" data-index="defaultBranch" />
          <a-table-column :title="$t('最后同步时间')" data-index="lastSyncAt">
            <template #cell="{ record }">
              {{ record.lastSyncAt ? formatDate(record.lastSyncAt) : '-' }}
            </template>
          </a-table-column>
          <a-table-column :title="$t('状态')" data-index="status" />
          <a-table-column :title="$t('操作')" align="center">
            <template #cell="{ record }">
              <a-space>
                <a-button type="text" size="small" @click="openModal(record)">
                  <template #icon><icon-edit /></template>
                  {{ $t('编辑') }}
                </a-button>
                <a-popconfirm
                  :content="$t('确定要删除这个仓库吗？')"
                  @ok="handleDelete(record.id)"
                >
                  <a-button type="text" status="danger" size="small">
                    <template #icon><icon-delete /></template>
                    {{ $t('删除') }}
                  </a-button>
                </a-popconfirm>
              </a-space>
            </template>
          </a-table-column>
        </template>
      </a-table>
    </a-card>

    <a-modal
      v-model:visible="modalVisible"
      :title="editingId ? $t('编辑仓库') : $t('添加仓库')"
      @ok="handleSubmit"
      @cancel="closeModal"
    >
      <a-form ref="formRef" :model="form" :rules="rules" layout="vertical">
        <a-form-item field="name" :label="$t('仓库名称')">
          <a-input v-model="form.name" :placeholder="$t('请输入仓库名称')" />
        </a-form-item>
        <a-form-item field="url" :label="$t('仓库地址')">
          <a-input v-model="form.url" :placeholder="$t('请输入仓库地址')" />
        </a-form-item>
        <a-form-item field="token" :label="$t('访问令牌')">
          <a-input-password
            v-model="form.token"
            :placeholder="$t('请输入访问令牌')"
          />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<style scoped>
  .warehouse-container {
    padding: 20px;
  }

  .general-card {
    margin-bottom: 20px;
  }
</style>

// devopsfront/src/pages/warehouse/index.tsx
import React, { useEffect, useState } from 'react';
import { Button, Card, Form, Input, Modal, Popconfirm, Space, Table, message } from 'antd';
import { PlusOutlined, DeleteOutlined, EditOutlined } from '@ant-design/icons';
import { useTranslation } from 'react-i18next';
import { useRequest } from 'ahooks';
import { createRepository, deleteRepository, getRepositories, updateRepository } from '@/services/warehouse';

const Warehouse: React.FC = () => {
  const { t } = useTranslation();
  const [form] = Form.useForm();
  const [modalVisible, setModalVisible] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);

  // 获取仓库列表
  const { data: repositories = [], refresh } = useRequest(getRepositories);

  // 处理表单提交
  const handleSubmit = async (values: any) => {
    try {
      if (editingId) {
        await updateRepository(editingId, values);
        message.success(t('仓库更新成功'));
      } else {
        await createRepository(values);
        message.success(t('仓库创建成功'));
      }
      setModalVisible(false);
      form.resetFields();
      refresh();
    } catch (error) {
      message.error(t('操作失败'));
    }
  };

  // 处理删除
  const handleDelete = async (id: number) => {
    try {
      await deleteRepository(id);
      message.success(t('仓库删除成功'));
      refresh();
    } catch (error) {
      message.error(t('删除失败'));
    }
  };

  // 表格列定义
  const columns = [
    {
      title: t('仓库名称'),
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: t('仓库地址'),
      dataIndex: 'url',
      key: 'url',
    },
    {
      title: t('默认分支'),
      dataIndex: 'defaultBranch',
      key: 'defaultBranch',
    },
    {
      title: t('最后同步时间'),
      dataIndex: 'lastSyncAt',
      key: 'lastSyncAt',
      render: (text: string) => text ? new Date(text).toLocaleString() : '-',
    },
    {
      title: t('状态'),
      dataIndex: 'status',
      key: 'status',
    },
    {
      title: t('操作'),
      key: 'action',
      render: (_: any, record: any) => (
        <Space>
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={() => {
              setEditingId(record.id);
              form.setFieldsValue(record);
              setModalVisible(true);
            }}
          >
            {t('编辑')}
          </Button>
          <Popconfirm
            title={t('确定要删除这个仓库吗？')}
            onConfirm={() => handleDelete(record.id)}
          >
            <Button type="link" danger icon={<DeleteOutlined />}>
              {t('删除')}
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div className="p-6">
      <Card
        title={t('仓库管理')}
        extra={
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={() => {
              setEditingId(null);
              form.resetFields();
              setModalVisible(true);
            }}
          >
            {t('添加仓库')}
          </Button>
        }
      >
        <Table
          columns={columns}
          dataSource={repositories}
          rowKey="id"
          pagination={false}
        />
      </Card>

      <Modal
        title={editingId ? t('编辑仓库') : t('添加仓库')}
        open={modalVisible}
        onCancel={() => {
          setModalVisible(false);
          form.resetFields();
        }}
        onOk={() => form.submit()}
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmit}
        >
          <Form.Item
            name="name"
            label={t('仓库名称')}
            rules={[{ required: true, message: t('请输入仓库名称') }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            name="url"
            label={t('仓库地址')}
            rules={[{ required: true, message: t('请输入仓库地址') }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            name="token"
            label={t('访问令牌')}
            rules={[{ required: true, message: t('请输入访问令牌') }]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default Warehouse;
